### ISSUE TITLE
Tutorial fails with Missing DLLs

### ISSUE THREAD

**Issue by titusz** [mherrmann/fbs-tutorial#4]
Trying the tutorial it fails for me on Win10 at `python -m fbs freeze`. I get a lot of warnings:
`15655 WARNING: lib not found: api-ms-win-crt-*`
and then a failure with:
`FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Windows\\System32\\api-ms-win-crt-multibyte-l1-1-0.dll'`

Any suggestions what to look for to fix this?

**Comment by mherrmann** [comment]
Do you have a file `api-ms-win-crt-*.dll` anywhere on your system?

**Comment by mherrmann** [comment]
(And in particular `api-ms-win-crt-multibyte-l1-1-0.dll`.)

**Comment by titusz** [comment]
yes multiple versions of it ... but not in system32 ... I even put a copy there and it still fails with the same error... very strange

**Comment by mherrmann** [comment]
It still fails with `FileNotFoundError: ...api-ms-win-crt-multibyte-l1-1-0.dll` even after you put the file there?

**Comment by mherrmann** [comment]
And where - in which paths - are your versions / copies of the file please?

**Comment by titusz** [comment]
Yes...
![image](https://user-images.githubusercontent.com/278556/36041773-ef0512ce-0dc9-11e8-9d04-20043d53263c.png)

**Comment by titusz** [comment]
This is where I have copies:
![image](https://user-images.githubusercontent.com/278556/36041832-14e419c2-0dca-11e8-8dc6-f43dd473ba9f.png)

**Comment by mherrmann** [comment]
Very strange... And when you do

    python

and then

    from shutil import copy
    copy(r'c:\Windows\System32\api-ms-win-crt-multibyte-l1-1-0.dll', r'C:\Users\titusz\Code\fbstest')

?

**Comment by mherrmann** [comment]
And maybe when you run the command prompts as Administrator?

**Comment by titusz** [comment]
This is weird... yes it also fails ... even with admin console:
![image](https://user-images.githubusercontent.com/278556/36042201-5d354d44-0dcb-11e8-81a7-299d30906457.png)

even copy pasted the dll filename from explorer to make sure there are no typos.
I also tried other files from System32 folder ... also not able to copy ...
Maybe because python is installed to nonstandard C:\Python35\ path ... I do a reinstall

**Comment by titusz** [comment]
Did a reinstall of Python 3.5.4 32-bit... now it fails with: `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\titusz\\Code\\Envs\\fbstest\\Scripts\\python3.dll'`
There is only a python35.dll in that folder for my fresh installation.

**Comment by mherrmann** [comment]
Do you have a full stack trace?

**Comment by titusz** [comment]
```
Traceback (most recent call last):
  File "C:\Users\titusz\AppData\Local\Programs\Python\Python35-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\titusz\AppData\Local\Programs\Python\Python35-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\titusz\Code\Envs\fbstest\lib\site-packages\fbs\__main__.py", line 4, in <module>
    main()
  File "C:\Users\titusz\Code\Envs\fbstest\lib\site-packages\fbs\cmdline.py", line 17, in main
    args.cmd()
  File "C:\Users\titusz\Code\Envs\fbstest\lib\site-packages\fbs\builtin_commands.py", line 35, in freeze
    freeze_windows()
  File "C:\Users\titusz\Code\Envs\fbstest\lib\site-packages\fbs\freeze\windows.py", line 27, in freeze_windows
    copy(join(dirname(sys.executable), dll_name), path('${freeze_dir}'))
  File "C:\Users\titusz\Code\Envs\fbstest\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\titusz\Code\Envs\fbstest\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\titusz\\Code\\Envs\\fbstest\\Scripts\\python3.dll'
```

**Comment by mherrmann** [comment]
Are you using the default Python from python.org or something else like Anaconda?

**Comment by titusz** [comment]
Default python from your tutorial link ... the 32-bit installer
![image](https://user-images.githubusercontent.com/278556/36043677-68aa4990-0dd0-11e8-81d0-36ae271fd53f.png)

**Comment by mherrmann** [comment]
Does it work when you delete the lines

    python_dlls = (
        'python%s.dll' % sys.version_info.major,
        'python%s%s.dll' % (sys.version_info.major, sys.version_info.minor)
    )
    for dll_name in python_dlls:
        remove(path('${freeze_dir}/' + dll_name))
        copy(join(dirname(sys.executable), dll_name), path('${freeze_dir}'))

in `C:\Users\titusz\Code\Envs\fbstest\lib\site-packages\fbs\freeze\windows.py`?

**Comment by titusz** [comment]
Yes i am back to the `FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Windows\\System32\\api-ms-win-crt-multibyte-l1-1-0.dll`.  I can copy some of the files from System32 via python... but not all. Must be some permission thing.

**Comment by titusz** [comment]
I got the freeze working, by removing the code as you suggested and adding `C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86` to the `path` . [This](https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/problem-with-universal-runtime-on-windows-10-pro/9fda2f7d-5cf8-4906-a542-77147e557d5d?auth=1) helped. Should we close this issue or is this something that should be mentioned in the tutorial. I like the idea of "cross-platform desktop apps in minutes, not months" very much :)

**Comment by mherrmann** [comment]
Glad you like it :-) I'll update fbs so it handles this case better, or tells the user install the Windows 10 SDK.

One thing that I'd still need your help with please: You got a `FileNotFoundError: python3.dll`. But you do get a `python3.dll` in `target\Tutorial` after `python -m fbs freeze` right? Where else on your system do you have `python3.dll`?

**Comment by titusz** [comment]
Yes with the deleted lines as suggested I get a `python3.dll`. My `venv/Scripts` folder does only have `python35.dll` and no `python3.dll`. The `venv` was created via PyCharm (if that matters). The `python3.dll` that ends up in the freeze is from the python base installation: `c:\Users\username\AppData\Local\Programs\Python\Python35-32\python3.dll`

**Comment by mherrmann** [comment]
Okay. I just released a new version of fbs and the tutorial that should help with the issue you encountered:

1. It searches more locations for `python3.dll` to (hopefully) avoid the `FileNotFoundError`.
2. If `api-ms-win-crt-*.dll` can't be found, it gives a helpful error message along the lines of the [link](https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/problem-with-universal-runtime-on-windows-10-pro/9fda2f7d-5cf8-4906-a542-77147e557d5d?auth=1) you posted.

Could I ask you to test this @titusz?

1. [Download](https://github.com/mherrmann/fbs-tutorial/archive/master.zip) the latest version of the tutorial.
2. Use PyCharm as before to create the virtual environment and install the requirements.
3. Run `python -m fbs freeze`. 

Hopefully it should be more helpful now. Please do let me know!

Thanks,
M

**Comment by titusz** [comment]
Just ran a test and I can confirm that the new version works fine. 👍

**Comment by mherrmann** [comment]
Great, thanks!

**Comment by atlas4292** [comment]
I am getting this error even after installing the SDK. Have run `fbs freeze` in both powershell and administrator command prompt and still getting this error. Full stack trace:

`Traceback (most recent call last): `
 ` File "C:\Python37\Scripts\fbs-script.py", line 11, in <module>
    load_entry_point('fbs==0.9.0', 'console_scripts', 'fbs')() `
 ` File "c:\python37\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()`
  `File "c:\python37\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)`
  `File "c:\python37\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)`
  `File "c:\python37\lib\site-packages\fbs\freeze\windows.py", line 22, in freeze_windows
    _add_missing_dlls()`
  `File "c:\python37\lib\site-packages\fbs\freeze\windows.py", line 71, in _add_missing_dlls
    ) from None`

`FileNotFoundError: Could not find api-ms-win-crt-multibyte-l1-1-0.dll on your PATH. If you are on Windows 10, you may have to install the Windows 10 SDK from https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk. Otherwise, try installing KB2999226 from https://support.microsoft.com/en-us/kb/2999226. In both cases, add the directory containing api-ms-win-crt-multibyte-l1-1-0.dll to your PATH environment variable afterwards. If there are 32 and 64 bit versions of the DLL, use the 64 bit one (because that's the bitness of your current Python interpreter). `


SOLVED: Added to User PATH environment variable (NOTE: System Environment PATH already contained necessary key value when this error occurred)

**Comment by mherrmann** [comment]
Which Python version are you using? And which Python versions does fbs support?

**Comment by atlas4292** [comment]
> Which Python version are you using? And which Python versions does fbs support?

Hi Michael! Yes this issue was later identified after solving this one and the executable would not run. `fbs freeze` runs (the command itself) successfully regardless of the Python version. While the generated output in the target folder does *not* work due to the versioning as you said, this is *not* the underlying cause of this issue. I have updated with a "solved" at the bottom for anyone who might come across this post. My Windows permissions are layered across many aspects and so it is easy to forget the necessity behind the separation of the users environment variables and the systems. For *most* general Windows users, this will never happen.
